// Mocks generated by Mockito 5.4.2 from annotations
// in advice/test/features/advice/presentation/bloc/advice_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:advice/core/entities/failure.dart' as _i6;
import 'package:advice/features/advice/domain/entities/advice_entity.dart'
    as _i7;
import 'package:advice/features/advice/domain/repository/advice_repository.dart'
    as _i2;
import 'package:advice/features/advice/domain/usecases/advice_usecases.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAdviceRepository_0 extends _i1.SmartFake
    implements _i2.AdviceRepository {
  _FakeAdviceRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdviceUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdviceUseCases extends _i1.Mock implements _i4.AdviceUseCases {
  @override
  _i2.AdviceRepository get adviceRepository => (super.noSuchMethod(
        Invocation.getter(#adviceRepository),
        returnValue: _FakeAdviceRepository_0(
          this,
          Invocation.getter(#adviceRepository),
        ),
        returnValueForMissingStub: _FakeAdviceRepository_0(
          this,
          Invocation.getter(#adviceRepository),
        ),
      ) as _i2.AdviceRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.AdviceEntity>> getAdvice() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdvice,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.AdviceEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.AdviceEntity>(
          this,
          Invocation.method(
            #getAdvice,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, _i7.AdviceEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.AdviceEntity>(
          this,
          Invocation.method(
            #getAdvice,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.AdviceEntity>>);
}
